# GET http://127.0.0.1:8000/orders/2
# POST  http://127.0.0.1:8000/orders/ HTTP/1.1
# content-type: application/json

# {
#     "product_id": "99999999999",
#     "buyer": "ddddddddd"
# }
POST http://127.0.0.1:8000/api/v2/orders/create/ HTTP/1.1
Content-Type: application/json
Authorization: token 14ed82ac1d3475ea447f7c91a2c0d1c8eebe254b

{
    "product_id": "2222222222222222222222",
    "cancel_flag": "0"
}